### PR TITLE
workflow to publish package with github packages

### PR DESCRIPTION
**Pull request by hoyelo**
https://github.com/InvisibleCommerce/shipped-suite-react-native-client-sdk/issues/26

### CODE REVIEW

**Comment by stevenou** [comment]
hmmm, I think I don't 100% understand how GitHub packages works.

does normal `npm install` or `yarn add` command work with GitHub packages out of the box? or does a user need to add GitHub packages registry to their project in order for it to work (e.g. add/change `.npmrc` with GitHub packages as the registry)?

if it's the latter, then maybe we should stick to npmjs but just start scoping our packages.

**Comment by hoyelo** [comment]
> 

They just need update the package name, you can check the document [here](https://docs.github.com/en/packages/quickstart).

After published, the package name may be changed from `react-native-shipped-suite-sdk` to `@InvisibleCommerce/react-native-shipped-suite-sdk@1.0.0`.
Screenshot 2023-03-29 at 11 57 56

**Comment by stevenou** [comment]
yeah, so it seems they would need to change `.npmrc` to use GitHub packages registry instead of npmjs. I think we should just use npmjs with scoped packages.

**Comment by hoyelo** [comment]
> yeah, so it seems they would need to change `.npmrc` to use GitHub packages registry instead of npmjs. I think we should just use npmjs with scoped packages.

okay, so we can close this pull request first?

**Comment by stevenou** [comment]
yes

**Pull request closed without merging**
